spring:
  config:
    activate:
      on-profile: jdbc
    import: optional:file:.env[.properties]
  datasource:
    url: ${PG_URL_JDBC}
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
    name: adoption
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      schema-locations: classpath:/postgres/schema.sql